spring:
  profiles:
    default: dev
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    username: postgres
    password: 12345678
server:
  port: 8081
  error:
    include-message: always
jwt:
  key: ${JWT_KEY}
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: ${DB_URL_TEST}

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${DB_URL}
    username: postgres
    password: 12345678
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        boot:
          allow_jdbc_metadata_access: false
        dialect: org.hibernate.dialect.PostgreSQLDialect

---
spring:
  profiles:
    active: ${ACTIVE_PROFILE}